# ======================================================
# globals
# ls .bash_scripts/globals/ | xargs | sed 's/ /\n/g' | awk '{print "alias "$1"=\'bash $bash_scripts/globals/"$1"\'"}' | copyme
# ======================================================
alias asroot='bash $bash_scripts/globals/asroot'
alias b0='bash $bash_scripts/globals/b0'
alias b1='bash $bash_scripts/globals/b1'
alias bluetooth='bash $bash_scripts/globals/bluetooth'
alias brightness='bash $bash_scripts/globals/brightness'
alias c0='bash $bash_scripts/globals/c0'
alias c1='bash $bash_scripts/globals/c1'
alias camerastatus='bash $bash_scripts/globals/camerastatus'
alias chistory='bash $bash_scripts/globals/chistory'
alias dbar='bash $bash_scripts/globals/dbar'
alias dwifi='bash $bash_scripts/globals/dwifi'
alias falias='bash $bash_scripts/globals/falias'
alias ffind='bash $bash_scripts/globals/ffind'
alias fhistory='bash $bash_scripts/globals/fhistory'
alias fsignal='bash $bash_scripts/globals/fsignal'
alias killdbar='bash $bash_scripts/globals/killdbar'
alias layout='bash $bash_scripts/globals/layout'
alias lf='bash $bash_scripts/globals/lf'
alias m0='bash $bash_scripts/globals/m0'
alias m1='bash $bash_scripts/globals/m1'
alias msg='bash $bash_scripts/globals/msg'
alias oonboard='bash $bash_scripts/globals/oonboard'
alias prompt='bash $bash_scripts/globals/prompt'
alias refreshdbar='bash $bash_scripts/globals/refreshdbar'
alias refreshdunst='bash $bash_scripts/globals/refreshdunst'
alias rmf='bash $bash_scripts/globals/rmf'
alias rotation='bash $bash_scripts/globals/rotation'
alias rr='bash $bash_scripts/globals/rr'
alias s0='bash $bash_scripts/globals/s0'
alias s1='bash $bash_scripts/globals/s1'
alias setbrightness='bash $bash_scripts/globals/setbrightness'
alias setsound='bash $bash_scripts/globals/setsound'
alias smute='bash $bash_scripts/globals/smute'
alias sound='bash $bash_scripts/globals/sound'
alias sslock='bash $bash_scripts/globals/sslock'
alias ssuspend='bash $bash_scripts/globals/ssuspend'
alias stogglemute='bash $bash_scripts/globals/stogglemute'
alias sunmute='bash $bash_scripts/globals/sunmute'
alias updates='bash $bash_scripts/globals/updates'
alias wifi='bash $bash_scripts/globals/wifi'
alias wifiip='bash $bash_scripts/globals/wifiip'

# ======================================================
# dbar
# ls .bash_scripts/dbar/ | xargs | sed 's/ /\n/g' | awk '{print "alias dbar_"$1"=\'bash $bash_scripts/dbar/"$1"\'"}' | copyme
# ======================================================
alias dbar_battery='bash $bash_scripts/dbar/battery'
alias dbar_bluetooth='bash $bash_scripts/dbar/bluetooth'
alias dbar_brightness='bash $bash_scripts/dbar/brightness'
alias dbar_camera='bash $bash_scripts/dbar/camera'
alias dbar_cpu='bash $bash_scripts/dbar/cpu'
alias dbar_date='bash $bash_scripts/dbar/date'
alias dbar_memory='bash $bash_scripts/dbar/memory'
alias dbar_microphone='bash $bash_scripts/dbar/microphone'
alias dbar_thermal='bash $bash_scripts/dbar/thermal'
alias dbar_updates='bash $bash_scripts/dbar/updates'
alias dbar_volume='bash $bash_scripts/dbar/volume'
alias dbar_wifi='bash $bash_scripts/dbar/wifi'

# ======================================================
# dshortcuts
# ls .bash_scripts/dshortcuts/ | xargs | sed 's/ /\n/g' | awk '{print "alias dshortcuts_"$1"=\'bash $bash_scripts/dshortcuts/"$1"\'"}' | copyme
# ======================================================
alias dshortcuts_bluetooth='bash $bash_scripts/dshortcuts/bluetooth'
alias dshortcuts_border='bash $bash_scripts/dshortcuts/border'
alias dshortcuts_braven='bash $bash_scripts/dshortcuts/braven'
alias dshortcuts_bravep='bash $bash_scripts/dshortcuts/bravep'
alias dshortcuts_brightness='bash $bash_scripts/dshortcuts/brightness'
alias dshortcuts_firefoxn='bash $bash_scripts/dshortcuts/firefoxn'
alias dshortcuts_firefoxp='bash $bash_scripts/dshortcuts/firefoxp'
alias dshortcuts_gap='bash $bash_scripts/dshortcuts/gap'
alias dshortcuts_internet='bash $bash_scripts/dshortcuts/internet'
alias dshortcuts_layout='bash $bash_scripts/dshortcuts/layout'
alias dshortcuts_librewolfn='bash $bash_scripts/dshortcuts/librewolfn'
alias dshortcuts_librewolfp='bash $bash_scripts/dshortcuts/librewolfp'
alias dshortcuts_power='bash $bash_scripts/dshortcuts/power'
alias dshortcuts_qutebrowser='bash $bash_scripts/dshortcuts/qutebrowser'
alias dshortcuts_rotation='bash $bash_scripts/dshortcuts/rotation'
alias dshortcuts_sound='bash $bash_scripts/dshortcuts/sound'
alias dshortcuts_surf='bash $bash_scripts/dshortcuts/surf'
alias dshortcuts_toggle='bash $bash_scripts/dshortcuts/toggle'
alias dshortcuts_wifi='bash $bash_scripts/dshortcuts/wifi'

# ======================================================
# rofi
# ls .bash_scripts/rofi/ | xargs | sed 's/ /\n/g' | awk '{print "alias rofi_"$1"=\'bash $bash_scripts/rofi/"$1"\'"}' | copyme
# ======================================================
alias rofi_askpass='bash $bash_scripts/rofi/askpass'
alias rofi_brightness='bash $bash_scripts/rofi/brightness'
alias rofi_camera='bash $bash_scripts/rofi/camera'
alias rofi_filebrowser='bash $bash_scripts/rofi/filebrowser'
alias rofi_internet='bash $bash_scripts/rofi/internet'
alias rofi_launcher='bash $bash_scripts/rofi/launcher'
alias rofi_layout='bash $bash_scripts/rofi/layout'
alias rofi_menu='bash $bash_scripts/rofi/menu'
alias rofi_microphone='bash $bash_scripts/rofi/microphone'
alias rofi_power='bash $bash_scripts/rofi/power'
alias rofi_rotation='bash $bash_scripts/rofi/rotation'
alias rofi_runner='bash $bash_scripts/rofi/runner'
alias rofi_volume='bash $bash_scripts/rofi/volume'
alias rofi_window='bash $bash_scripts/rofi/window'
